project:
  type: website
  resources:
    - "posts/**/data/**"      # copy any file inside any .../data/ folder

website:
  title: "chrwittm.github.io"
  site-url: https://chrwittm.github.io/
  google-analytics: "G-GF3YYKQQNH"
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chrwittm
      - icon: twitter-x
        href: https://twitter.com/chrwittm
      - icon: linkedin
        href: https://de.linkedin.com/in/chrwittm
      - icon: file-earmark-code
        href: https://www.kaggle.com/christianwittmann
#      - icon: rss
#        href: blog.xml
format:
  html:
    theme: cosmo
    css: styles.css


