project:
  type: website

website:
  title: "chrwittm.github.io"
  site-url: https://chrwittm.github.io/
  google-analytics: "G-GF3YYKQQNH"
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chrwittm
      - icon: twitter
        href: https://twitter.com/chrwittm
#      - icon: rss
#        href: blog.xml
format:
  html:
    theme: cosmo
    css: styles.css



